# Generated by Django 5.1.5 on 2025-01-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("destination", "0002_review"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="destination",
            options={"ordering": ["-created_at"]},
        ),
    ]
