# Generated by Django 5.1.5 on 2025-02-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destination", "0006_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (0, "0 Star"),
                    (1, "1 Star"),
                    (2, "2 Star"),
                    (3, "3 Star"),
                    (4, "4 Star"),
                    (5, "5 Star"),
                ],
                default=0,
                null=True,
            ),
        ),
    ]
